[project]
name = "manimations"
version = "0.1.0"
description = "A collection of animations I created using the Manim library"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "manim>=0.19.0",
]
